import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import NextTopLoader from "nextjs-toploader";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import StoreProvider from "./storeProvider";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Charge App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { getUser, isAuthenticated } = getKindeServerSession();
  const user = await getUser();
  console.log("current user", await getUser());
  console.log("user is authenticated?", await isAuthenticated());
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <StoreProvider>
            <NextTopLoader />
            <Navbar user={user} />
            {children}
          </StoreProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
